import Head from "next/head";
import { CheckIcon, UserAddIcon, XIcon } from "@heroicons/react/solid";
import Table from "../components/table";
import Form from "../components/form";
import { useSelector, useDispatch } from "react-redux";
import { deleteAction, toggleChangeAction } from "../redux/reducer";
import { useQueryClient } from "react-query";
import { deleteUser, getUsers } from "../utils/helpers";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const queryclient = useQueryClient();
  const dispatch = useDispatch();

  const handleVisibleForm = () => {
    dispatch(toggleChangeAction());
  };

  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery("users", getUsers);
      await dispatch(deleteAction(null));
    }
  };

  const canclehandler = async () => {
    console.log("cancel");
    await dispatch(deleteAction(null));
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5">
        <h1 className="text-xl md:text-4xl text-center font-bold">
          Employee Management
        </h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handleVisibleForm}
              className="flex items-center justify-center gap-x-1 bg-indigo-500 text-white px-4 py-2 rounded-md hover:bg-indigo-600"
            >
              <UserAddIcon className="h-4 w-4" />
              Add Employee
            </button>
          </div>
          {deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}
        </div>

        {visible && <Form></Form>}

        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}

function DeleteComponent({ deletehandler, canclehandler }) {
  return (
    <div className="flex gap-5">
      <button>Are you sure?</button>
      <button
        onClick={deletehandler}
        className="flex items-center bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50"
      >
        Yes{" "}
        <span className="px-1">
          <XIcon className="text-white h-4 w-4" />
        </span>
      </button>
      <button
        onClick={canclehandler}
        className="flex items-center bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-gree-500 hover:border-green-500 hover:text-gray-50"
      >
        No{" "}
        <span className="px-1">
          <CheckIcon className="text-white h-4 w-4" />
        </span>
      </button>
    </div>
  );
}
